from app.extensions import db, ma


class cxccnc(db.Model):
    __tablename__ = "cxccnc"
    __table_args__ = {"extend_existing": True}

    # Definición de columnas
    ciacodigo = db.Column(db.String(2), primary_key=True, nullable=False)
    nccodigo = db.Column(db.String(18), primary_key=True, nullable=False)
    clicodigo = db.Column(db.String(6), nullable=False)
    loccodigo = db.Column(db.String(2), primary_key=True, nullable=False)
    garcodigo = db.Column(db.String(6), nullable=False)
    facnumfac = db.Column(db.String(18), nullable=False)
    ncabono = db.Column(db.Numeric(18, 2), nullable=False)
    seqcodigo = db.Column(db.String(3), nullable=False)
    seqmonto = db.Column(db.Integer, nullable=False)
    ncompcodigo = db.Column(db.String(18))
    ncdetalle = db.Column(db.String(255), nullable=False)
    ncfecemi = db.Column(db.DateTime, nullable=False)
    ncfecsys = db.Column(db.DateTime, nullable=False)
    nchorsys = db.Column(db.DateTime, nullable=False)
    ncmonto = db.Column(db.Numeric(18, 2), nullable=False)
    ncsaldo = db.Column(db.Numeric(18, 2), nullable=False)
    ncstatus = db.Column(db.String(1), nullable=False)
    ncsubtot = db.Column(db.Numeric(18, 2), nullable=False)
    moncodigo = db.Column(db.String(1), nullable=False)
    nctivacer = db.Column(db.Numeric(18, 2), nullable=False)
    nctivapor = db.Column(db.Numeric(18, 2), nullable=False)
    nctotiva = db.Column(db.Numeric(18, 2), nullable=False)
    ncusuisys = db.Column(db.String(10), nullable=False)
    vencodigo = db.Column(db.String(3))
    zoncodigo = db.Column(db.String(3))
    vencomision = db.Column(db.Numeric(18, 2))
    ventipcom = db.Column(db.String(1))
    nccambio = db.Column(db.Numeric(18, 2))
    tipoabono = db.Column(db.String(4))
    tranumbco = db.Column(db.String(18))
    bcocodigo = db.Column(db.String(3))
    trannumedoc = db.Column(db.String(16))
    ncfecventar = db.Column(db.DateTime)
    nccedula = db.Column(db.String(13))
    ncautoriza = db.Column(db.String(16))
    ncvoucher = db.Column(db.String(10))
    regnumero = db.Column(db.String(18))
    ncvalinter = db.Column(db.Numeric(16, 2), nullable=False, default=0.00)
    ncpordes = db.Column(db.Numeric(6, 2), nullable=False, default=0.00)
    ncdesglobal = db.Column(db.Numeric(18, 2), nullable=False, default=0.00)
    ncdesdirecto = db.Column(db.Numeric(18, 2), nullable=False, default=0.00)
    ncvalrec = db.Column(db.Numeric(18, 2), nullable=False, default=0.00)
    ncporiva = db.Column(db.Numeric(6, 2), nullable=False, default=0.00)
    ncporrec = db.Column(db.Numeric(6, 2), nullable=False, default=0.00)
    ncintmen = db.Column(db.Numeric(6, 2), nullable=False, default=0.00)
    cjacodigo = db.Column(db.String(3))
    reccodigo = db.Column(db.String(3))
    tarciacod = db.Column(db.String(2))
    tarclicod = db.Column(db.String(6))
    fasriserie01 = db.Column(db.String(3), nullable=False, default="001")
    fasriserie02 = db.Column(db.String(3), nullable=False, default="001")
    fasrisecini = db.Column(db.Numeric(18, 0), nullable=False, default=0)
    fasrisecfin = db.Column(db.Numeric(18, 0), nullable=False, default=0)
    fasriautfecemi = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    fasriautfecven = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    fasriautnumero = db.Column(db.String(49))
    sriserie01 = db.Column(db.String(3), nullable=False, default="001")
    sriserie02 = db.Column(db.String(3), nullable=False, default="001")
    srisecini = db.Column(db.Numeric(18, 0), nullable=False, default=0)
    srisecfin = db.Column(db.Numeric(18, 0), nullable=False, default=0)
    sriautfecemi = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    sriautfecven = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    sriautnumero = db.Column(db.String(49))
    audnumxml = db.Column(db.String(18))
    nclote = db.Column(db.Integer, default=0)
    ncfecven = db.Column(db.DateTime)
    leccodigo = db.Column(db.String(2))
    facrotdif = db.Column(db.Integer, default=0)
    faccuotasdif = db.Column(db.Integer, default=0)
    ncformulario = db.Column(db.String(20))
    ncrap = db.Column(db.String(20))
    integracodigo = db.Column(db.String(3), nullable=False)
    proyectocodigo = db.Column(db.String(6), nullable=False)
    pednumped = db.Column(db.String(18))
    tipcodigo = db.Column(db.String(3))
    ncnumero = db.Column(db.Numeric(18, 0), nullable=False, default=0)
    ncelectronica = db.Column(db.Integer, nullable=False, default=0)
    clinombre = db.Column(db.String(200))
    cliruc = db.Column(db.String(15))
    clidirec = db.Column(db.String(200))
    cliemail = db.Column(db.String(100))
    ciaciaruc = db.Column(db.String(15))
    ciaciadescri = db.Column(db.String(200))
    ciaciadirec = db.Column(db.String(200))
    ciaciatelefono1 = db.Column(db.String(30))
    ciaciaciudad = db.Column(db.String(30))
    ciaciapais = db.Column(db.String(30))
    locdescri = db.Column(db.String(200))
    locciadirec = db.Column(db.String(200))
    locciatelefono1 = db.Column(db.String(30))
    locciaciudad = db.Column(db.String(30))
    locciapais = db.Column(db.String(30))
    cianumresolucion = db.Column(db.String(10))
    ciaobligadocon = db.Column(db.Integer, nullable=False, default=0)
    numsolanusri = db.Column(db.String(10))
    codctblesri = db.Column(db.String(18))


class cxccnc_schema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = cxccnc
