# flake8: noqa
from app.extensions import db
from sqlalchemy import Column, String, Integer, DateTime, Numeric, Float
from app.extensions import ma


class cxpmprov(db.Model):
    __tablename__ = "cxpmprov"

    ciacodigo = Column(String(2), primary_key=True, nullable=False)
    procodigo = Column(String(6), primary_key=True, nullable=False)
    pronombre = Column(String(200), nullable=False)
    proruc = Column(String(20), nullable=False)
    prorepres = Column(String(40), nullable=False)
    propais = Column(String(20), nullable=False)
    prociudad = Column(String(20), nullable=False)
    procodpost = Column(String(20), nullable=True)
    prodirec = Column(String(200), nullable=False)
    proemail = Column(String(100), nullable=True)
    protelef1 = Column(String(15), nullable=True)
    protelef2 = Column(String(15), nullable=True)
    profax = Column(String(15), nullable=True)
    profacsri = Column(String(20), nullable=True)
    profacimp = Column(String(20), nullable=True)
    procredito = Column(Numeric(18, 2), nullable=True)
    prosaldosuc = Column(Numeric(18, 2), nullable=False)
    prosaldodol = Column(Numeric(18, 2), nullable=False)
    prostatus = Column(String(1), nullable=False)
    procalif = Column(String(1), nullable=True)
    pctacodigo = Column(String(30), nullable=True)
    pctadolar = Column(String(30), nullable=True)
    proesperjur = Column(Integer, nullable=False)
    proesconesp = Column(Integer, nullable=False)
    procambiaimp = Column(Integer, nullable=False)
    profecisys = Column(DateTime, nullable=False)
    prohorisys = Column(DateTime, nullable=False)
    prousuisys = Column(String(10), nullable=False)
    profecmsys = Column(DateTime, nullable=False)
    prohormsys = Column(DateTime, nullable=False)
    prousumsys = Column(String(10), nullable=False)
    tipocodigo = Column(String(3), nullable=True)
    prodiacre = Column(Integer, nullable=False)
    pctadevloc = Column(String(50), nullable=True)
    pctadevext = Column(String(50), nullable=True)
    prointerno = Column(Integer, nullable=True, default=0)
    prorucmat = Column(String(20), nullable=True)
    pronommat = Column(String(100), nullable=True)
    bcocodigo = Column(String(3), nullable=True)
    bcotipcta = Column(String(2), nullable=True)
    bconumcta = Column(String(20), nullable=True)
    procuo = Column(Integer, nullable=False, default=1)
    pctacodigoant = Column(String(30), nullable=True)
    pctacodigoncdev = Column(String(30), nullable=True)
    protarcre = Column(Integer, nullable=False, default=0)
    notcodigo = Column(String(3), nullable=True)
    proweb = Column(String(80), nullable=True)
    procelu = Column(String(15), nullable=True)
    procuota = Column(Numeric(18, 2), nullable=False, default=0)
    properiodoini = Column(DateTime, nullable=True)
    properiodofin = Column(DateTime, nullable=True)
    prodescuento = Column(Numeric(18, 2), nullable=False, default=0)
    pctacodigovia = Column(String(30), nullable=True)
    pctacodigocaj = Column(String(30), nullable=True)
    prolistaprecio = Column(Integer, nullable=False, default=1)
    proparterel = Column(String(1), nullable=False, default="N")
    protipcompra = Column(String(1), nullable=True)
    promontminimo = Column(Float, nullable=True)
    proaplicaGar = Column(String(1), nullable=False, default=0)
    progardias = Column(Integer, nullable=False, default=0)
    progarcondicion = Column(String(200), nullable=True)
    proaplicaContr = Column(String(1), nullable=False, default=0)
    procontrdias = Column(Integer, nullable=False, default=0)
    procontrfecini = Column(DateTime, nullable=True)
    procontrfecfin = Column(DateTime, nullable=True)
    procondentrega = Column(String(7), nullable=True)
    proobsentrega = Column(String(200), nullable=True)
    procondiciondsc = Column(String(200), nullable=True)
    proaplicarebate = Column(String(1), nullable=False, default=0)
    activicodigo = Column(String(3), nullable=True)
    prorebatedetalle = Column(String(200), nullable=True)


class cxpmprovSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = cxpmprov
