# flake8: noqa
from marshmallow import fields
from sqlalchemy import Index
from app.extensions import db
from app.extensions import ma


class Facpedpro(db.Model):
    __tablename__ = "facpedpro"

    ciacodigo = db.Column(db.String(2), primary_key=True)
    pednumped = db.Column(db.String(18), primary_key=True)
    loccodigo = db.Column(db.String(2), primary_key=True)
    prosecuen = db.Column(db.Integer, primary_key=True)
    facnumfac = db.Column(db.String(18))
    pedtipo = db.Column(db.String(2))
    factippag = db.Column(db.String(3))
    moncodigo = db.Column(db.String(1))
    clicodigo = db.Column(db.String(6))
    garcodigo = db.Column(db.String(6))
    peddirent = db.Column(db.String(100))
    pedcambio = db.Column(db.Numeric(18, 2))
    pedfecemi = db.Column(db.DateTime)
    pedfecven = db.Column(db.DateTime)
    pedtivacer = db.Column(db.Numeric(18, 2))
    pedtivapor = db.Column(db.Numeric(18, 2))
    pedsubtot = db.Column(db.Numeric(18, 2))
    pediva = db.Column(db.Numeric(18, 2))
    pedtotal = db.Column(db.Numeric(18, 2))
    pedstatus = db.Column(db.String(1))
    peddetalle = db.Column(db.String(1000))
    pedfecisys = db.Column(db.DateTime)
    pedhorisys = db.Column(db.DateTime)
    pedusuisys = db.Column(db.String(10))
    pedestisys = db.Column(db.String(30))
    pedfecmsys = db.Column(db.DateTime)
    pedhormsys = db.Column(db.DateTime)
    pedusumsys = db.Column(db.String(10))
    pedestmsys = db.Column(db.String(30))
    pedusudes = db.Column(db.String(10))
    vencodigo = db.Column(db.String(3))
    zoncodigo = db.Column(db.String(3))
    pedpordes = db.Column(db.Numeric(18, 2))
    peddesglobal = db.Column(db.Numeric(18, 2))
    peddesdirecto = db.Column(db.Numeric(18, 2))
    pedrecargo = db.Column(db.Numeric(18, 2))
    tipcodigo = db.Column(db.String(3))
    pedporrec = db.Column(db.Numeric(6, 2))
    pedporiva = db.Column(db.Numeric(6, 2))
    pedvalantici = db.Column(db.Numeric(16, 2))
    forintmen = db.Column(db.Numeric(6, 2))
    pedvalinter = db.Column(db.Numeric(16, 2))
    fordias = db.Column(db.Integer)
    fortipo = db.Column(db.String(2))
    forcuotas = db.Column(db.Integer)
    foraplianti = db.Column(db.Integer)
    foranticipo = db.Column(db.Numeric(6, 2))
    foraplirango = db.Column(db.Integer)
    formondesde = db.Column(db.Numeric(16, 2))
    formonhasta = db.Column(db.Numeric(16, 2))
    forapligrac = db.Column(db.Integer)
    fordiasgrac = db.Column(db.Integer)
    forcuoinigr = db.Column(db.Integer)
    pedusuanti = db.Column(db.String(10))
    codcodigo = db.Column(db.String(6))
    adinumero = db.Column(db.String(18))
    pednumadi = db.Column(db.Integer)
    pedvaladi = db.Column(db.Numeric(18, 2))
    pedapliiva = db.Column(db.Integer)
    pedconser = db.Column(db.Integer)
    pedlockser = db.Column(db.String(1))
    pedvehi = db.Column(db.Integer)
    audnumxml = db.Column(db.String(18))
    integracodigo = db.Column(db.String(3))
    proyectocodigo = db.Column(db.String(6))
    foraprocredito = db.Column(db.Integer)
    foraprologistica = db.Column(db.Integer)
    foraprocliente = db.Column(db.Integer)
    pedaprocredito = db.Column(db.Integer)
    pedaprologistica = db.Column(db.Integer)
    pedaprocliente = db.Column(db.Integer)
    pedproyecto = db.Column(db.Integer)
    pedsolsinstock = db.Column(db.Integer)
    pedsinstock = db.Column(db.Integer)
    forpromocion = db.Column(db.Integer)
    fordescuento = db.Column(db.Numeric(7, 2))
    regcodigo = db.Column(db.String(3))
    ciucodigo = db.Column(db.String(3))
    procodigo = db.Column(db.String(3))
    pedusuaped = db.Column(db.String(10))
    pedfecaped = db.Column(db.DateTime)
    pedhoraped = db.Column(db.DateTime)
    pedestaped = db.Column(db.String(60))
    pedusuapro = db.Column(db.String(10))
    pedfecapro = db.Column(db.DateTime)
    pedhorapro = db.Column(db.DateTime)
    pedestapro = db.Column(db.String(60))
    pedvallincre = db.Column(db.Numeric(18, 2))

    # Agregar un Ã­ndice a la columna pednumped
    # __table_args__ = (
    #     Index('_dta_index_facped_7_2106646748__K1_K72_K8_K71_K88_K6_K30_K31_K2_3_4_5_7_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_',
    #         loccodigo,facnumfac,pedtipo,moncodigo,garcodigo,peddirent,pedcambio,pedfecemi,pedfecven,pedtivacer,pedtivapor,pedsubtot,pediva,pedtotal,pedstatus,peddetalle,pedfecisys,pedhorisys,pedusuisys,pedestisys,pedfecmsys,pedhormsys,pedusumsys,pedestmsys,pedusudes,pedpordes,peddesglobal,peddesdirecto,pedrecargo,tipcodigo,pedporrec,pedporiva,pedvalantici,forintmen,pedvalinter,fordias,fortipo,forcuotas,foraplianti,foranticipo,foraplirango,formondesde,formonhasta,forapligrac,fordiasgrac,forcuoinigr,pedusuanti,codcodigo,adinumero,pednumadi,pedvaladi,pedapliiva,pedconser,pedlockser,pedvehi,foraprocredito,foraprologistica,foraprocliente,pedaprocredito,pedaprologistica,pedaprocliente,pedproyecto,pedsolsinstock,pedsinstock,forpromocion,fordescuento,regcodigo,procodigo,prosecuen,ciacodigo,proyectocodigo,clicodigo,integracodigo,ciucodigo,factippag,vencodigo,zoncodigo,pednumped),
    # )


class FacpedproSchema(ma.SQLAlchemyAutoSchema):
    # pedfecemi  = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecven  = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecisys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhorisys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecmsys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhormsys = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecaped = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhoraped = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedfecapro = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')
    # pedhorapro = fields.DateTime(format='%Y-%m-%d %H:%M:%S.%f')

    class Meta:
        model = Facpedpro
