# flake8: noqa
from app.extensions import db
from app.extensions import ma


class Fatpedpro(db.Model):
    __tablename__ = "fatpedpro"

    ciacodigo = db.Column(db.String(2), primary_key=True)
    pednumped = db.Column(db.String(18), primary_key=True)
    pedsecuen = db.Column(db.Integer, primary_key=True)
    prosecuen = db.Column(db.Integer, primary_key=True)
    facnumfac = db.Column(db.String(18))
    pedtipo = db.Column(db.String(2), nullable=False)
    pedapliiva = db.Column(db.Integer, nullable=False, default=0)
    factippag = db.Column(db.String(3), nullable=False)
    moncodigo = db.Column(db.String(1), nullable=False)
    pedcambio = db.Column(db.Numeric(16, 2), nullable=False, default=0)
    pedfecemi = db.Column(db.DateTime, nullable=False)
    clicodigo = db.Column(db.String(6), nullable=False)
    loccodigo = db.Column(db.String(2), nullable=False)
    cliprecio = db.Column(db.Integer, nullable=False, default=0)
    pedstatus = db.Column(db.String(1), nullable=False)
    bodcodigo = db.Column(db.String(3))
    invcodigo = db.Column(db.String(2))
    artcodigo = db.Column(db.String(15))
    precodigo = db.Column(db.String(2))
    coscodigo = db.Column(db.String(30))
    lincodigo = db.Column(db.String(20), nullable=False)
    vencodigo = db.Column(db.String(3))
    zoncodigo = db.Column(db.String(3))
    sercodigo = db.Column(db.String(3))
    pedcantidad = db.Column(db.Numeric(20, 5), nullable=False, default=0)
    pedcosto = db.Column(db.Numeric(20, 5), nullable=False, default=0)
    pedcostodol = db.Column(db.Numeric(20, 5), nullable=False, default=0)
    pedpreven = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedvaldesglo = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedvaldesc = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedvalrec = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pediva = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedvaliva = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedvalor = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedvaltot = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedfecisys = db.Column(db.DateTime, nullable=False)
    pedhorisys = db.Column(db.DateTime, nullable=False)
    pedusuisys = db.Column(db.String(10), nullable=False)
    pedestisys = db.Column(db.String(30), nullable=False)
    pedfecmsys = db.Column(db.DateTime, nullable=False)
    pedhormsys = db.Column(db.DateTime, nullable=False)
    pedusumsys = db.Column(db.String(10), nullable=False)
    pedestmsys = db.Column(db.String(30), nullable=False)
    tipcodigo = db.Column(db.String(3))
    pedpordesc = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    pedusudesc = db.Column(db.String(10))
    artaplipro = db.Column(db.Integer)
    pedvalinter = db.Column(db.Numeric(16, 5), nullable=False, default=0)
    medcodigo = db.Column(db.String(3))
    marcodigo = db.Column(db.String(5))
    artpeso = db.Column(db.Numeric(20, 8), nullable=False, default=0)
    artserie = db.Column(db.Integer)
    artservicio = db.Column(db.Integer)
    artexpins = db.Column(db.Integer)
    audnumxml = db.Column(db.String(18))
    artfaccero = db.Column(db.Integer, nullable=False)
    integracodigo = db.Column(db.String(3), nullable=False)
    proyectocodigo = db.Column(db.String(6), nullable=False)
    pedfecposent = db.Column(db.DateTime)
    pedcantfacturado = db.Column(db.Numeric(18, 6), nullable=False, default=0)
    pedpordescori = db.Column(db.Numeric(16, 6), nullable=False, default=0)
    pedprecioori = db.Column(db.Numeric(20, 6), nullable=False, default=0)
    jefecodigo = db.Column(db.String(6))
    artdescri = db.Column(db.String(50))
    pedusuaped = db.Column(db.String(10))
    pedfecaped = db.Column(db.DateTime)
    pedhoraped = db.Column(db.DateTime)
    pedestaped = db.Column(db.String(60))
    pedusuapro = db.Column(db.String(10))
    pedfecapro = db.Column(db.DateTime)
    pedhorapro = db.Column(db.DateTime)
    pedestapro = db.Column(db.String(60))


class FatpedproSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Fatpedpro
