# flake8: noqa
from app.extensions import db
from app.extensions import ma


class Intart(db.Model):
    __tablename__ = "intart"

    ciacodigo = db.Column(db.String(2), primary_key=True)
    tranumero = db.Column(db.String(18), primary_key=True)
    trafecha = db.Column(db.DateTime, nullable=False)
    trahora = db.Column(db.DateTime, nullable=False)
    invcodigo = db.Column(db.String(2), nullable=False)
    bodcodigo = db.Column(db.String(3), nullable=False, primary_key=True)
    invcodtransing = db.Column(db.String(2))
    bodcodtransing = db.Column(db.String(3))
    invcodtransegr = db.Column(db.String(2))
    bodcodtransegr = db.Column(db.String(3))
    lincodigo = db.Column(db.String(20), nullable=False)
    artcodigo = db.Column(db.String(15), nullable=False, primary_key=True)
    relcodigo = db.Column(db.String(50))
    clicodigo = db.Column(db.String(6))
    trasecuencia = db.Column(db.Integer, default=1, nullable=False, primary_key=True)
    ordnumero = db.Column(db.String(18))
    trastatus = db.Column(db.String(1), nullable=False)
    precodigo = db.Column(db.String(2), nullable=False)
    preequivale = db.Column(db.Integer)
    medcodigo = db.Column(db.String(3), nullable=False)
    prepeso = db.Column(db.Numeric(18, 2), nullable=False)
    prebasica = db.Column(db.Integer)
    tracodigo = db.Column(db.String(3), nullable=False)
    tratipo = db.Column(db.String(7), nullable=False)
    trasigno = db.Column(db.String(1), nullable=False)
    tracantidad = db.Column(db.Numeric(18, 6), nullable=False)
    tracanttrans = db.Column(db.Numeric(18, 6), default=0)
    tracostocompra = db.Column(db.Numeric(18, 8))
    tracostocomdol = db.Column(db.Numeric(18, 8))
    tracostoinventario = db.Column(db.Numeric(18, 2), nullable=False)
    tracostoinvdol = db.Column(db.Numeric(18, 8))
    tracodpreven = db.Column(db.Integer)
    traprecioventa = db.Column(db.Numeric(18, 2))
    tracantasig = db.Column(db.Numeric(18, 2))
    trafecisys = db.Column(db.DateTime, nullable=False)
    trahorisys = db.Column(db.DateTime, nullable=False)
    trausuisys = db.Column(db.String(10), nullable=False)
    trafecmsys = db.Column(db.DateTime, nullable=False)
    trahormsys = db.Column(db.DateTime, nullable=False)
    trausumsys = db.Column(db.String(10), nullable=False)
    tradato = db.Column(db.String(6))
    marcodigo = db.Column(db.String(5))
    tracantant = db.Column(db.Numeric(16, 6), default=0)
    tracodciarel = db.Column(db.String(2))
    audnumxml = db.Column(db.String(18))
    audnumxmltrans = db.Column(db.String(18))
    artpercha = db.Column(db.String(60))
    facsecuen = db.Column(db.Integer, default=0, nullable=False)
    facnumero = db.Column(db.String(25))
    artcostocomrep = db.Column(db.Numeric(20, 8))
    artcostorep = db.Column(db.Numeric(20, 8))
    tracantexcedente = db.Column(db.Numeric(18, 6), default=0, nullable=False)
    tracantexcedeacep = db.Column(db.Numeric(18, 6), default=0, nullable=False)
    COSCODIGO = db.Column(db.String(30))
    bahcodigo = db.Column(db.String(10), nullable=False)
    nivcodigo = db.Column(db.String(10), nullable=False)
    embcodigo = db.Column(db.String(10), nullable=False)
    toncodigo = db.Column(db.String(10), nullable=False)
    izoncodigo = db.Column(db.String(10), nullable=False)
    pascodigo = db.Column(db.String(10), nullable=False)
    poscodigo = db.Column(db.String(10), nullable=False)
    artcantconver = db.Column(db.Numeric(18, 6))
    embpieza = db.Column(db.Integer)
    embmetros2 = db.Column(db.Numeric(18, 2))
    artcantconfirmar = db.Column(db.Numeric(18, 6), default=0, nullable=False)
    artvalidaN1Fec = db.Column(db.DateTime)
    artvalidaN1Hor = db.Column(db.DateTime)
    artvalidaN1Usu = db.Column(db.String(10))
    artvalidaN1Est = db.Column(db.String(50))
    artvalidaN1InvAnt = db.Column(db.String(2))
    artvalidaN1BodAnt = db.Column(db.String(3))
    embmetros3 = db.Column(db.Numeric(18, 2))
    bahcodigodestino = db.Column(db.String(10))
    nivcodigodestino = db.Column(db.String(10))
    izoncodigodestino = db.Column(db.String(10))
    pascodigodestino = db.Column(db.String(10))
    poscodigodestino = db.Column(db.String(10))
    sgapicking = db.Column(db.String(18))
    clifinal = db.Column(db.String(6))
    sgaegrpick = db.Column(db.String(18))
    artpickcantidad = db.Column(db.Numeric(18, 6), default=0)
    artpickcantconver = db.Column(db.Numeric(18, 6), default=0)
    clipicking = db.Column(db.String(6))
    sgacansolfac = db.Column(db.String(18))
    artcantconvertconfirmar = db.Column(db.Numeric(18, 6), default=0, nullable=False)
    sgapickingsecuen = db.Column(db.Numeric(18, 0), default=0, nullable=False)
    palletid = db.Column(db.String(18))


class IntartSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model: Intart
