# flake8: noqa
from app.extensions import db
from app.extensions import ma


class siaccia(db.Model):
    __tablename__ = "siaccia"

    ciacodigo = db.Column(db.String(2), primary_key=True, nullable=False)
    ciaanioejer = db.Column(db.Integer, nullable=True)
    ciaauxcredito = db.Column(db.String(35), nullable=True)
    ciacontador = db.Column(db.String(35), nullable=True)
    ciadescri = db.Column(db.String(200), nullable=False)
    ciaalias = db.Column(db.String(30), nullable=True)
    ciaruc = db.Column(db.String(15), nullable=True)
    ciadirec = db.Column(db.String(200), nullable=False)
    ciafax = db.Column(db.String(15), nullable=True)
    ciafecisys = db.Column(db.DateTime, nullable=True)
    ciafecminacc = db.Column(db.DateTime, nullable=True)
    ciafecmsys = db.Column(db.DateTime, nullable=True)
    ciaforcencos = db.Column(db.String(30), nullable=True)
    ciaforlin = db.Column(db.String(30), nullable=True)
    ciagerente = db.Column(db.String(35), nullable=True)
    ciahorisys = db.Column(db.DateTime, nullable=True)
    ciahormsys = db.Column(db.DateTime, nullable=True)
    cianivelescc = db.Column(db.Integer, nullable=True)
    cianiveleslin = db.Column(db.Integer, nullable=True)
    ciapresidente = db.Column(db.String(35), nullable=True)
    ciarecsalmen = db.Column(db.Integer, nullable=True)
    ciaregcont = db.Column(db.String(10), nullable=True)
    ciastatus = db.Column(db.String(1), nullable=True)
    ciatelefono1 = db.Column(db.String(15), nullable=True)
    ciatelefono2 = db.Column(db.String(15), nullable=True)
    ciausuisys = db.Column(db.String(10), nullable=True)
    ciausumsys = db.Column(db.String(10), nullable=True)
    ciavigilancia = db.Column(db.String(35), nullable=True)
    ciaciudad = db.Column(db.String(30), nullable=True)
    ciapais = db.Column(db.String(30), nullable=True)
    ciaescontesp = db.Column(db.Integer, nullable=True)
    ciaemail = db.Column(db.String(70), nullable=True)
    ciaweb = db.Column(db.String(70), nullable=True)
    ciaanioinicon = db.Column(db.Integer, nullable=True)
    ciaforpre = db.Column(db.String(30), nullable=True)
    cianivelespre = db.Column(db.Integer, nullable=True)
    ciadiasnc = db.Column(db.Integer, default=0, nullable=True)
    ciacedgerente = db.Column(db.String(10), nullable=True)
    ciahelpart = db.Column(db.String(1), nullable=True)
    ciacantfor = db.Column(db.String(20), nullable=True)
    ciacostfor = db.Column(db.String(20), nullable=True)
    ciavehele = db.Column(db.Integer, nullable=True)
    ciapresupuesto = db.Column(db.Integer, default=0, nullable=False)
    ciafecinipre = db.Column(db.DateTime, nullable=True)
    ciaforcta = db.Column(db.String(40), nullable=True)
    cianivelescta = db.Column(db.Integer, default=0, nullable=False)
    ciasrirazon = db.Column(db.String(200), nullable=False)
    ciasrifono = db.Column(db.String(9), nullable=True)
    ciasrifax = db.Column(db.String(9), nullable=True)
    ciasriemail = db.Column(db.String(60), nullable=True)
    ciasriruccontador = db.Column(db.String(13), nullable=True)
    ciatipoidengerente = db.Column(db.String(1), nullable=True)
    ciasridirmatriz = db.Column(db.String(60), nullable=True)
    ciasridocautventas = db.Column(db.String(2), nullable=True)
    ciasrinotdebventas = db.Column(db.String(2), nullable=True)
    ciasrinotcreventas = db.Column(db.String(2), nullable=True)
    ciasriretfueventas = db.Column(db.String(5), nullable=True)
    ciacodlocmatriz = db.Column(db.String(2), nullable=True)
    generacodian = db.Column(db.Integer, nullable=True)
    coscodigo = db.Column(db.String(30), nullable=True)
    aplitransing = db.Column(db.Integer, default=0, nullable=False)
    apliserie = db.Column(db.Integer, default=0, nullable=False)
    codclisec = db.Column(db.Integer, default=0, nullable=False)
    codprosec = db.Column(db.Integer, default=0, nullable=False)
    ciasecuencliente = db.Column(db.Numeric(10, 0), default=0, nullable=False)
    ciasecuenproveedor = db.Column(db.Numeric(10, 0), default=0, nullable=False)
    ciasecuentarjeta = db.Column(db.String(7), nullable=True)
    codartsec = db.Column(db.Integer, default=0, nullable=False)
    ciasecuenartventa = db.Column(db.Numeric(15, 0), default=0, nullable=False)
    ciasecuenarticulo = db.Column(db.Numeric(13, 0), default=0, nullable=False)
    ciaactualizaprecios = db.Column(db.Integer, default=0, nullable=False)
    cianumresolucion = db.Column(db.String(10), nullable=True)
    ciafecresolucion = db.Column(db.DateTime, nullable=True)
    CiaNivelOrg = db.Column(db.Integer, nullable=True)
    ciafororg = db.Column(db.String(30), nullable=True)
    cianumvend = db.Column(db.Integer, nullable=True)
    ciasolautfactcxp = db.Column(db.Integer, default=0, nullable=False)
    ciaaproautfactcxp = db.Column(db.Integer, default=0, nullable=False)
    ciasolautanticxp = db.Column(db.Integer, default=0, nullable=False)
    ciaaproautanticxp = db.Column(db.Integer, default=0, nullable=False)
    ciasolautpagocxp = db.Column(db.Integer, default=0, nullable=False)
    ciaaproautpagocxp = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocimport = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocserv = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocgasta = db.Column(db.Integer, default=0, nullable=False)
    ciaaaoclocal = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocgastasoc = db.Column(db.Integer, default=0, nullable=False)
    ciafacitemrep = db.Column(db.Integer, default=0, nullable=False)
    ciasecuenemple = db.Column(db.Integer, default=0, nullable=False)
    ciasecuencargo = db.Column(db.Integer, default=0, nullable=False)
    ciavalprecost = db.Column(db.Integer, default=0, nullable=False)
    ciaporretiva = db.Column(db.Numeric(6, 2), default=0, nullable=False)
    ciaporretfuente = db.Column(db.Numeric(6, 2), default=0, nullable=False)
    ciactapagolote = db.Column(db.String(30), nullable=True)
    ciatipoocfaclote = db.Column(db.String(3), nullable=True)
    ciaivaservicio = db.Column(db.String(3), nullable=True)
    ciafacelectronica = db.Column(db.String(50), nullable=True)
    versionfac = db.Column(db.DateTime, nullable=True)
    ciapdfelectronica = db.Column(db.String(50), nullable=True)
    versionpdf = db.Column(db.DateTime, nullable=True)
    ciaambienteelectronica = db.Column(db.Integer, default=0, nullable=False)
    srimicroempresa = db.Column(db.String(1), default="N", nullable=False)
    sricartera = db.Column(db.String(1), default="N", nullable=False)
    sriguia = db.Column(db.String(1), default="N", nullable=False)
    sriagenteretencion = db.Column(db.String(1), default="N", nullable=False)
    sriagenteretencionnumres = db.Column(db.String(25), nullable=True)
    sricorreoffice = db.Column(db.String(1), default="N", nullable=False)
    sricopiacorreo = db.Column(db.String(1), default="N", nullable=False)
    srimensajefactura = db.Column(db.String(1), default="N", nullable=False)
    srissltls = db.Column(db.String(1), default="N", nullable=False)
    srioffini = db.Column(db.DateTime, nullable=True)
    sriofffin = db.Column(db.DateTime, nullable=True)
    ciaaaocliqcomloc = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocliqcomimp = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocliqcomser = db.Column(db.Integer, default=0, nullable=False)
    ciaaaocppe = db.Column(db.Integer, default=0, nullable=False)
    ciacobrapuntos = db.Column(db.Integer, default=0, nullable=False)
    ciacobracupos = db.Column(db.Integer, default=0, nullable=False)
    ciacobrafundacion = db.Column(db.Integer, default=0, nullable=False)
    ciancbeneficiario = db.Column(db.Integer, default=0, nullable=False)
    ciainmobiliaria = db.Column(db.Integer, default=0, nullable=False)
    ciancdevcxccia = db.Column(db.Integer, default=0, nullable=False)
    ciadiasretencion = db.Column(db.Numeric(12, 0), default=0, nullable=False)
    ciadiasemitirretencion = db.Column(db.Numeric(12, 0), default=30, nullable=False)
    ciapropina = db.Column(db.Boolean, default=0, nullable=False)
    ciacontabilidad = db.Column(db.Boolean, default=1, nullable=False)
    ciaemailproforma = db.Column(db.String(100), nullable=True)
    ciaclaveproforma = db.Column(db.String(50), nullable=True)
    cliciagrupo = db.Column(db.String(50), nullable=True)
    ciasolautclcxp = db.Column(db.Integer, default=0, nullable=False)
    ciaaproautclcxp = db.Column(db.Integer, default=0, nullable=False)
    cialogo = db.Column(db.LargeBinary, nullable=True)
    ciaselloagua = db.Column(db.LargeBinary, nullable=True)
    ciaivaporproducto = db.Column(db.Integer, nullable=True)
    cialistprecdefweb = db.Column(db.Integer, nullable=False)
    ciafacDeVariosLoc = db.Column(db.Integer, nullable=False)


class siacciaSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = siaccia
