# flake8: noqa
from app.extensions import db, PrimaryKeyConstraint
from app.extensions import ma


class ViewProducto(db.Model):
    __tablename__ = "view_inmart"
    # __table_args__ = {'schema': 'SiacPracticasa.dbo'}

    # ciacodigo = db.Column(db.String(2))
    # invcodigo = db.Column(db.String(2))
    # artcodigo = db.Column(db.String(15))
    # #artprodven =  db.column(db.db.Integereger)
    # artdescri = db.Column(db.String(200))
    # artprecventa1 = db.Column (db.Numeric(precision=18, scale=8))
    # lincodigo = db.Column(db.String(20))
    # lindescri = db.Column(db.String(100))
    # linlindes = db.Column(db.String(20))
    # marcodigo = db.Column(db.String(5))
    # mardescri = db.Column(db.String(100))
    # precodigo = db.Column(db.String(2))
    # predescri = db.Column(db.String(100))
    # medcodigo = db.Column(db.String(3))
    # meddescri = db.Column(db.String(100))

    ciacodigo = db.Column(db.String)
    invcodigo = db.Column(db.String)
    artcodigo = db.Column(db.String)
    artnumparte = db.Column(db.String)
    artdescri = db.Column(db.String)
    lincodigo = db.Column(db.String)
    marcodigo = db.Column(db.String)
    medcodigo = db.Column(db.String)
    artpeso = db.Column(db.Numeric)
    artminimo = db.Column(db.Numeric)
    artmaximo = db.Column(db.Numeric)
    artdiasrep = db.Column(db.Integer)
    artdiasseg = db.Column(db.Integer)
    artfrelleg = db.Column(db.Integer)
    precodigo = db.Column(db.String)
    artcantinicial = db.Column(db.Numeric)
    artcantactual = db.Column(db.Numeric)
    artcanttranfer = db.Column(db.Numeric)
    artcantimporta = db.Column(db.Numeric)
    artstatus = db.Column(db.String)
    artprodven = db.Column(db.Integer)
    artservicio = db.Column(db.Integer)
    artapliiva = db.Column(db.Integer)
    artcobraiva = db.Column(db.Numeric)
    artcostoinicial = db.Column(db.Numeric)
    artcostoactual = db.Column(db.Numeric)
    artcostoinidol = db.Column(db.Numeric)
    artcostoactdol = db.Column(db.Numeric)
    artprecventa1 = db.Column(db.Numeric)
    artprecventa2 = db.Column(db.Numeric)
    artprecventa3 = db.Column(db.Numeric)
    artprecventa4 = db.Column(db.Numeric)
    artprecventa5 = db.Column(db.Numeric)
    artprecventa6 = db.Column(db.Numeric)
    artprevendol1 = db.Column(db.Numeric)
    artprevendol2 = db.Column(db.Numeric)
    artprevendol3 = db.Column(db.Numeric)
    artprevendol4 = db.Column(db.Numeric)
    artprevendol5 = db.Column(db.Numeric)
    artprevendol6 = db.Column(db.Numeric)
    artpordes = db.Column(db.Numeric)
    artmondes = db.Column(db.Numeric)
    artaplipro = db.Column(db.Integer)
    artexpins = db.Column(db.Integer)
    artfecinipro = db.Column(db.DateTime)
    arthorinipro = db.Column(db.DateTime)
    artfecfinpro = db.Column(db.DateTime)
    arthorfinpro = db.Column(db.DateTime)
    vencomision = db.Column(db.Numeric)
    refcomision = db.Column(db.Numeric)
    artfecisys = db.Column(db.DateTime)
    arthorisys = db.Column(db.DateTime)
    artusuisys = db.Column(db.String)
    artfecmsys = db.Column(db.DateTime)
    arthormsys = db.Column(db.DateTime)
    artusumsys = db.Column(db.String)
    artfeccos = db.Column(db.DateTime)
    arthorcos = db.Column(db.DateTime)
    artusucos = db.Column(db.String)
    artfecpre = db.Column(db.DateTime)
    arthorpre = db.Column(db.DateTime)
    artusupre = db.Column(db.String)
    artdesporcant = db.Column(db.Integer)
    artserie = db.Column(db.Integer)
    artseriedesp = db.Column(db.Integer)
    artdiasgarven = db.Column(db.Integer)
    artdiasgarcom = db.Column(db.Integer)
    artapliret = db.Column(db.Integer)
    artporrec = db.Column(db.Integer)
    artmonrec = db.Column(db.Integer)
    artvehiculo = db.Column(db.Integer)
    paiscodigo = db.Column(db.String)
    tipserie = db.Column(db.String)
    artmoddesc = db.Column(db.Integer)
    artdecimal = db.Column(db.Integer)
    sercodigo = db.Column(db.String)
    artconcentra = db.Column(db.String)
    artcantrecip = db.Column(db.String)
    artregissani = db.Column(db.String)
    artnumregsan = db.Column(db.String)
    artcomentari = db.Column(db.String)
    artalias = db.Column(db.String)
    artporvidutil = db.Column(db.Numeric)
    artlote = db.Column(db.Integer)
    artfaccero = db.Column(db.Integer)
    artetiqueta = db.Column(db.String)
    artprov1 = db.Column(db.String)
    artprov2 = db.Column(db.String)
    artprov3 = db.Column(db.String)
    artprov4 = db.Column(db.String)
    invdescri = db.Column(db.String)
    lindescri = db.Column(db.String)
    linlindes = db.Column(db.String)
    linnivel = db.Column(db.Integer)
    mardescri = db.Column(db.String)
    predescri = db.Column(db.String)
    meddescri = db.Column(db.String)
    artbloqueocompra = db.Column(db.Integer)
    artweb = db.Column(db.String)
    jefecodigo = db.Column(db.String)
    jefedescri = db.Column(db.String)
    artobserva = db.Column(db.String)
    coscodigo = db.Column(db.String)
    artarancel = db.Column(db.String)
    artporpartida = db.Column(db.Numeric)
    artcodpartida = db.Column(db.String)
    artimpseriecer = db.Column(db.Integer)
    artsincosto = db.Column(db.Integer)
    artcantcergarantia = db.Column(db.Integer)
    artcodigo2 = db.Column(db.String)
    artcodbarra = db.Column(db.String)
    imagen = db.Column(db.Integer)
    documento = db.Column(db.Integer)
    sustituido = db.Column(db.Integer)
    sustituto = db.Column(db.Integer)
    stock = db.Column(db.Numeric)
    codigo2 = db.Column(db.Integer)
    barras = db.Column(db.Integer)
    calfcodigo = db.Column(db.String)
    inencodigo = db.Column(db.String)
    arttemperatura = db.Column(db.String)
    inendescrip = db.Column(db.String)
    iva = db.Column(db.Numeric)
    # tmpcantidadimpresion=db.Column( db.db.Integereger)

    # campo temporal del modelo Producto para la cantidad de etiquetas a imprimir
    # tmpcantidadimpresion = db.Column(db.db.Integereger)

    __table_args__ = (
        PrimaryKeyConstraint("ciacodigo", "invcodigo", "artcodigo", name="pk_inmart"),
        # {'schema': 'SiacPracticasa.dbo'}
    )

    def serialize(self):
        return {
            "artcodigo": self.artcodigo,
            "ciacodigo": self.ciacodigo,
            "invcodigo": self.invcodigo,
            "precodigo": self.precodigo,
        }


class ViewProductoSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model: ViewProducto
