from app.extensions import db, ma


class view_inv_cabecera_solicitud_egreso(db.Model):
    __tablename__ = "view_inv_cabecera_solicitud_egreso"
    ciacodigo = db.Column(db.String, primary_key=True)
    loccodigo = db.Column(db.String, primary_key=True)
    sgasolegr = db.Column(db.String, primary_key=True)
    sgaorigen = db.Column(db.String)
    sgagenepor = db.Column(db.String)
    sgadescri = db.Column(db.String)
    sgasoling = db.Column(db.String)
    trannumero = db.Column(db.String)
    motcodigo = db.Column(db.String)
    sgafecsol = db.Column(db.DateTime)
    sgahorsol = db.Column(db.DateTime)
    sgaususol = db.Column(db.String)
    sgaestsol = db.Column(db.String)
    clicodigo = db.Column(db.String)
    procodigo = db.Column(db.String)
    sgafecenvio = db.Column(db.DateTime)
    sgahorenvio = db.Column(db.DateTime)
    sgacomenenvio = db.Column(db.String)
    agencodigosol = db.Column(db.String)
    agecodrelextsol = db.Column(db.String)
    agencodigoenv = db.Column(db.String)
    agecodrelextsenv = db.Column(db.String)
    condescrienv = db.Column(db.String)
    concodrelextenv = db.Column(db.String)
    sgaulttranumrecep = db.Column(db.String)
    sgaultfecegr = db.Column(db.DateTime)
    sgaulthoregr = db.Column(db.DateTime)
    sgaultusuegr = db.Column(db.String)
    sgaultestegr = db.Column(db.String)
    sgastatus = db.Column(db.String)
    sgafecapro = db.Column(db.DateTime)
    sgahorapro = db.Column(db.DateTime)
    sgausuapro = db.Column(db.String)
    sgaestapro = db.Column(db.String)
    sgacomenapro = db.Column(db.String)
    sgafeccie = db.Column(db.DateTime)
    sgahorcie = db.Column(db.DateTime)
    sgausucie = db.Column(db.String)
    sgaestcie = db.Column(db.String)
    sgacomencie = db.Column(db.String)
    sgafecmsys = db.Column(db.DateTime)
    sgahormsys = db.Column(db.DateTime)
    sgausumsys = db.Column(db.String)
    sgaestmsys = db.Column(db.String)
    idwmsInp = db.Column(db.String)
    WERKS = db.Column(db.String)
    BSART = db.Column(db.String)
    BANFN = db.Column(db.String)
    DED = db.Column(db.String)
    BOD = db.Column(db.String)
    MO = db.Column(db.String)
    US = db.Column(db.String)
    BLDAT = db.Column(db.DateTime)
    MBLNR = db.Column(db.String)
    motdescripcion = db.Column(db.String)
    mottipo = db.Column(db.String)
    locdescri = db.Column(db.String)
    clinombre = db.Column(db.String)
    cliruc = db.Column(db.String)
    clidirec = db.Column(db.String)
    clitelef1 = db.Column(db.String)
    clitelef2 = db.Column(db.String)
    cliintersec = db.Column(db.String)
    invcodigo = db.Column(db.String)
    pronombre = db.Column(db.String)
    proruc = db.Column(db.String)
    protelef1 = db.Column(db.String)
    protelef2 = db.Column(db.String)
    procelu = db.Column(db.String)
    sgacansol = db.Column(db.Float)
    sgacanegr = db.Column(db.Float)
    sgacansolpicking = db.Column(db.Float)
    agendescrisol = db.Column(db.String)
    agendescrienv = db.Column(db.String)


class view_inv_cabecera_solicitud_egreso_schema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = view_inv_cabecera_solicitud_egreso
