# flake8: noqa
from app.extensions import db
from app.extensions import ma


class view_inv_cabecera_solicitud_ingreso(db.Model):
    __tablename__ = "view_inv_cabecera_solicitud_ingreso"

    ciacodigo = db.Column(db.String, primary_key=True)
    loccodigo = db.Column(db.String, primary_key=True)
    sgasoling = db.Column(db.String, primary_key=True)
    sgastatus = db.Column(db.String)
    sgaorigen = db.Column(db.String)
    sgagenepor = db.Column(db.String)
    sgadescri = db.Column(db.String)
    sgasolegr = db.Column(db.String)
    tranumero = db.Column(db.String)
    motcodigo = db.Column(db.String)
    sgafecsol = db.Column(db.DateTime)
    sgahorsol = db.Column(db.DateTime)
    sgaususol = db.Column(db.String)
    sgaestsol = db.Column(db.String)
    clicodigo = db.Column(db.String)
    procodigo = db.Column(db.String)
    sgafecllegada = db.Column(db.DateTime)
    sgahorllegada = db.Column(db.DateTime)
    sgacomenllegada = db.Column(db.String)
    sgaulttranumrecep = db.Column(db.String)
    sgaultfecrecep = db.Column(db.DateTime)
    sgaulthorrecep = db.Column(db.DateTime)
    sgaultusurecep = db.Column(db.String)
    sgaultestrecep = db.Column(db.String)
    sgastatus = db.Column(db.String)
    sgafecapro = db.Column(db.DateTime)
    sgahorapro = db.Column(db.DateTime)
    sgausuapro = db.Column(db.String)
    sgaestapro = db.Column(db.String)
    sgacomenapro = db.Column(db.String)
    sgafeccie = db.Column(db.DateTime)
    sgahorcie = db.Column(db.DateTime)
    sgausucie = db.Column(db.String)
    sgaestcie = db.Column(db.String)
    sgacomencie = db.Column(db.String)
    sgafecmsys = db.Column(db.DateTime)
    sgahormsys = db.Column(db.DateTime)
    sgausumsys = db.Column(db.String)
    sgaestmsys = db.Column(db.String)
    idwmsInp = db.Column(db.String)
    EBELN = db.Column(db.String)
    BWART = db.Column(db.String)
    SOBKZ = db.Column(db.String)
    BLDAT = db.Column(db.DateTime)
    LFSNR = db.Column(db.String)
    BKTXT = db.Column(db.String)
    idwmsOut = db.Column(db.String)
    MBLNR = db.Column(db.String)
    motdescripcion = db.Column(db.String)
    mottipo = db.Column(db.String)
    locdescri = db.Column(db.String)
    clinombre = db.Column(db.String)
    cliruc = db.Column(db.String)
    clidirec = db.Column(db.String)
    clitelef1 = db.Column(db.String)
    clitelef2 = db.Column(db.String)
    cliintersec = db.Column(db.String)
    invcodigo = db.Column(db.String)
    pronombre = db.Column(db.String)
    proruc = db.Column(db.String)
    protelef1 = db.Column(db.String)
    protelef2 = db.Column(db.String)
    procelu = db.Column(db.String)
    sgacansol = db.Column(db.String)
    sgacanrec = db.Column(db.String)


class view_inv_cabecera_solicitud_ingreso_schema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = view_inv_cabecera_solicitud_ingreso
